#pragma once

// Bloodhunt (1.X) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

namespace SDK
{
//---------------------------------------------------------------------------
//Enums
//---------------------------------------------------------------------------

// UserDefinedEnum ShopTypeEnum.ShopTypeEnum
enum class EShopTypeEnum : uint8_t
{
	ShopTypeEnum__NewEnumerator0   = 0,
	ShopTypeEnum__NewEnumerator1   = 1,
	ShopTypeEnum__NewEnumerator2   = 2,
	ShopTypeEnum__NewEnumerator3   = 3,
	ShopTypeEnum__NewEnumerator4   = 4,
	ShopTypeEnum__NewEnumerator5   = 5,
	ShopTypeEnum__NewEnumerator36  = 6,
	ShopTypeEnum__NewEnumerator45  = 7,
	ShopTypeEnum__NewEnumerator46  = 8,
	ShopTypeEnum__NewEnumerator6   = 9,
	ShopTypeEnum__NewEnumerator8   = 10,
	ShopTypeEnum__NewEnumerator9   = 11,
	ShopTypeEnum__NewEnumerator10  = 12,
	ShopTypeEnum__NewEnumerator7   = 13,
	ShopTypeEnum__NewEnumerator42  = 14,
	ShopTypeEnum__NewEnumerator11  = 15,
	ShopTypeEnum__NewEnumerator12  = 16,
	ShopTypeEnum__NewEnumerator13  = 17,
	ShopTypeEnum__NewEnumerator14  = 18,
	ShopTypeEnum__NewEnumerator15  = 19,
	ShopTypeEnum__NewEnumerator16  = 20,
	ShopTypeEnum__NewEnumerator17  = 21,
	ShopTypeEnum__NewEnumerator18  = 22,
	ShopTypeEnum__NewEnumerator19  = 23,
	ShopTypeEnum__NewEnumerator20  = 24,
	ShopTypeEnum__NewEnumerator21  = 25,
	ShopTypeEnum__NewEnumerator22  = 26,
	ShopTypeEnum__NewEnumerator43  = 27,
	ShopTypeEnum__NewEnumerator24  = 28,
	ShopTypeEnum__NewEnumerator23  = 29,
	ShopTypeEnum__NewEnumerator44  = 30,
	ShopTypeEnum__NewEnumerator25  = 31,
	ShopTypeEnum__NewEnumerator26  = 32,
	ShopTypeEnum__NewEnumerator27  = 33,
	ShopTypeEnum__NewEnumerator28  = 34,
	ShopTypeEnum__NewEnumerator29  = 35,
	ShopTypeEnum__NewEnumerator30  = 36,
	ShopTypeEnum__NewEnumerator31  = 37,
	ShopTypeEnum__NewEnumerator32  = 38,
	ShopTypeEnum__NewEnumerator33  = 39,
	ShopTypeEnum__NewEnumerator34  = 40,
	ShopTypeEnum__NewEnumerator35  = 41,
	ShopTypeEnum__NewEnumerator38  = 42,
	ShopTypeEnum__NewEnumerator39  = 43,
	ShopTypeEnum__NewEnumerator40  = 44,
	ShopTypeEnum__NewEnumerator41  = 45,
	ShopTypeEnum__NewEnumerator47  = 46,
	ShopTypeEnum__NewEnumerator48  = 47,
	ShopTypeEnum__NewEnumerator49  = 48,
	ShopTypeEnum__NewEnumerator50  = 49,
	ShopTypeEnum__NewEnumerator51  = 50,
	ShopTypeEnum__NewEnumerator52  = 51,
	ShopTypeEnum__NewEnumerator53  = 52,
	ShopTypeEnum__NewEnumerator54  = 53,
	ShopTypeEnum__NewEnumerator55  = 54,
	ShopTypeEnum__NewEnumerator56  = 55,
	ShopTypeEnum__NewEnumerator57  = 56,
	ShopTypeEnum__NewEnumerator58  = 57,
	ShopTypeEnum__NewEnumerator59  = 58,
	ShopTypeEnum__NewEnumerator60  = 59,
	ShopTypeEnum__NewEnumerator61  = 60,
	ShopTypeEnum__NewEnumerator62  = 61,
	ShopTypeEnum__NewEnumerator63  = 62,
	ShopTypeEnum__NewEnumerator64  = 63,
	ShopTypeEnum__NewEnumerator65  = 64,
	ShopTypeEnum__NewEnumerator66  = 65,
	ShopTypeEnum__NewEnumerator67  = 66,
	ShopTypeEnum__NewEnumerator68  = 67,
	ShopTypeEnum__NewEnumerator69  = 68,
	ShopTypeEnum__NewEnumerator70  = 69,
	ShopTypeEnum__NewEnumerator71  = 70,
	ShopTypeEnum__NewEnumerator72  = 71,
	ShopTypeEnum__NewEnumerator73  = 72,
	ShopTypeEnum__NewEnumerator74  = 73,
	ShopTypeEnum__NewEnumerator75  = 74,
	ShopTypeEnum__NewEnumerator76  = 75,
	ShopTypeEnum__NewEnumerator77  = 76,
	ShopTypeEnum__NewEnumerator78  = 77,
	ShopTypeEnum__NewEnumerator79  = 78,
	ShopTypeEnum__NewEnumerator80  = 79,
	ShopTypeEnum__NewEnumerator81  = 80,
	ShopTypeEnum__NewEnumerator82  = 81,
	ShopTypeEnum__NewEnumerator83  = 82,
	ShopTypeEnum__NewEnumerator84  = 83,
	ShopTypeEnum__NewEnumerator85  = 84,
	ShopTypeEnum__NewEnumerator86  = 85,
	ShopTypeEnum__NewEnumerator87  = 86,
	ShopTypeEnum__NewEnumerator88  = 87,
	ShopTypeEnum__NewEnumerator89  = 88,
	ShopTypeEnum__NewEnumerator90  = 89,
	ShopTypeEnum__NewEnumerator91  = 90,
	ShopTypeEnum__NewEnumerator92  = 91,
	ShopTypeEnum__NewEnumerator93  = 92,
	ShopTypeEnum__NewEnumerator94  = 93,
	ShopTypeEnum__NewEnumerator95  = 94,
	ShopTypeEnum__NewEnumerator96  = 95,
	ShopTypeEnum__NewEnumerator97  = 96,
	ShopTypeEnum__NewEnumerator98  = 97,
	ShopTypeEnum__NewEnumerator99  = 98,
	ShopTypeEnum__NewEnumerator100 = 99,
	ShopTypeEnum__NewEnumerator101 = 100,
	ShopTypeEnum__NewEnumerator102 = 101,
	ShopTypeEnum__NewEnumerator103 = 102,
	ShopTypeEnum__NewEnumerator104 = 103,
	ShopTypeEnum__NewEnumerator105 = 104,
	ShopTypeEnum__NewEnumerator106 = 105,
	ShopTypeEnum__NewEnumerator107 = 106,
	ShopTypeEnum__NewEnumerator108 = 107,
	ShopTypeEnum__NewEnumerator109 = 108,
	ShopTypeEnum__ShopTypeEnum_MAX = 109
};


}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
